### ISSUE TITLE
AWS Infrastructure Provider

### ISSUE THREAD

**Issue by scotwells** [datum-cloud/enhancements#102]
### Overview

Create a new infrastructure provider that supports provisioning infrastructure in AWS. Initially we will target provisioning instances, networks, subnets, and any other dependent resources needed to support provisioning an instance in AWS.

### Expected Impact

- Datum Cloud users will be able to provision their Datum Cloud infrastructure using their AWS account.
- Serves as an integration point with AWS so we can introduce AWS VPCs as a network context on Datum Cloud Galactic VPCs.

**Comment by joshlreese** [comment]
Northflank supports leveraging [cross-account roles](https://northflank.com/docs/v1/application/bring-your-own-cloud/aws-on-northflank#add-your-account-with-a-cross-account-role) to authenticate with AWS. This appears to be set up to enable a Northflank-owned and managed role to assume the custom role in the user's AWS account, which is configured with permissions provided to the user in the Northflank interface.

**Comment by joshlreese** [comment]
> Research notes on https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/
> 
> * Enables identity federation via OIDC
> * IAM role permits access to call the `AssumeRoleWithWebIdentity` API to obtain temporary credentials.
> 
> Open question - how can we leverage this with Crossplane when running in GKE?

After some tweaks to the shell script provided in this example, I've confirmed that I can:

1. Create an IAM Role in AWS with a Trust Policy to allow tokens issued for a GCP service account to assume the role.
2. Obtain a token from GCP via Workload Identity that represents that GCP service account.
4. Use the token from GCP to obtain temporary AWS credentials for the role created in step 1.

Next I plan to install the Crossplane AWS components in a GKE cluster and test [IAM Role Chaining](https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/AUTHENTICATION.md#iam-role-chaining-configuration) with the goal of first assuming the role created in step 1 above, then another role that will represent a Datum Project's specific AWS role. It may be possible to skip the chaining step, but I'd like to think through what that might look like a bit more.

**Comment by joshlreese** [comment]
Design consideration that came up during testing - Unlike GCP, AWS endpoints are regional, including the STS service. We should make sure to consider how we ensure regional failures do not result in an inability to influence resources in unaffected regions.

The AWS ProviderConfig has the ability to influence endpoints used, which may be useful: https://github.com/crossplane-contrib/provider-upjet-aws/blob/71f83d818b966c5575ba005736453c2fd011bf21/apis/v1beta1/types.go#L20

**Comment by joshlreese** [comment]
Yep, it was a configuration issue. I had the following ProviderConfig:

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-datum-project-iam-roles
spec:
  credentials:
    source: IRSA
  assumeRoleChain:
    - roleARN: arn:aws:iam::194722439963:role/jreese-test
```

Just needed to remove the `assumeRoleChain` for this test, since the AWS SDK will already assume the role defined in the `AWS_ROLE_ARN` environment variable which the Crossplane AWS pods are configured with.

I was able to successfully create an IAM Role via Crossplane:

```
% kubectl get roles.iam.aws.upbound.io jreese-test-role        
NAME               SYNCED   READY   EXTERNAL-NAME      AGE
jreese-test-role   True     True    jreese-test-role   33s
```

From the AWS console:

<img width="983" alt="Image" src="https://github.com/user-attachments/assets/ae4e46a7-5f46-441f-adeb-6c88610e2b35" />

**Comment by joshlreese** [comment]
> Design consideration that came up during testing - Unlike GCP, AWS endpoints are regional, including the STS service. We should make sure to consider how we ensure regional failures do not result in an inability to influence resources in unaffected regions.

Relevant info on this topic: https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/global-services.html

**Comment by joshlreese** [comment]
> > > Design consideration that came up during testing - Unlike GCP, AWS endpoints are regional, including the STS service. We should make sure to consider how we ensure regional failures do not result in an inability to influence resources in unaffected regions.
> > 
> > 
> > Relevant info on this topic: https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/global-services.html
> 
> Documentation on [STS Regional Endpoints](https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html#feature-sts-regionalized-endpoints-sdk-compat) indicates that fallback behavior would be toward the global endpoint, if the regional endpoint is not available. I'll make a note of this in the enhancement to cover in testing.

Reading through the code, it appears that any managed resource with `spec.forProvider.region` should result in Crossplane interacting directly with that region for those APIs. We'll be wiring a value into this field for resources that need it via the settings in Location resources.

I still plan to confirm this, and fallback for the STS endpoint, but this seems promising.

https://github.com/crossplane-contrib/provider-upjet-aws/blob/8520c765359ae63acf283d0f60dbc512d1d4332f/internal/clients/provider_config.go#L96-L106

**Comment by joshlreese** [comment]
Some notes from this afternoon:

## Wiring in secrets

There are two options that exist, [Secrets Manager](https://aws.amazon.com/secrets-manager/pricing/) and [Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html). 

Secrets Manager costs ~$0.40/secret/replica/month. https://aws.amazon.com/secrets-manager/pricing/

Systems Manager Parameter Store appears to be free for standard parameters. There may be a KMS cost incurred, which would be upon create and read operations. Further research is necessary here. https://aws.amazon.com/systems-manager/pricing/#Parameter-Store

Considering this, I have successfully tested Systems Manager Parameter Store and have adapted the [secrets population script](https://github.com/datum-cloud/infra-provider-gcp/blob/main/internal/controller/cloudinit/populate_secrets.py) to read from these APIs to write out instance secrets.

## AMIs

AMIs are per region - I have tested the Flatcar linux AMI, as it includes kubelet, and would allow us to follow the pattern of laying down a static pod to launch container based instances with. https://www.flatcar.org/docs/latest/installing/cloud/aws-ec2/

We'd need to map Datum images, which are logically global, to regional AMIs. This can happen either via discovery, or configuration.

## Instance Profiles

Similar to launching a GCP instance with a specific service account, an EC2 instance can be launched with an [Instance Profile](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html). This profile is what permits the credentials provided to the instance to interact with Amazon APIs. In the case of testing today, I granted it permission to read the specific secret parameter created - mimicking what would be done for a workload's secret.

<details>
<summary>Instance Profile JSON</summary>

```json
{
    "InstanceProfiles": [
        {
            "Path": "/",
            "InstanceProfileName": "jreese-test-instance-profile",
            "InstanceProfileId": "AIPAS2VS4UMNV5KSV5Q2P",
            "Arn": "arn:aws:iam::194722439963:instance-profile/jreese-test-instance-profile",
            "CreateDate": "2025-06-19T22:00:13+00:00",
            "Roles": [
                {
                    "Path": "/",
                    "RoleName": "jreese-test-instance-profile",
                    "RoleId": "AROAS2VS4UMNSRQNYARHD",
                    "Arn": "arn:aws:iam::194722439963:role/jreese-test-instance-profile",
                    "CreateDate": "2025-06-19T22:00:13+00:00",
                    "AssumeRolePolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Principal": {
                                    "Service": "ec2.amazonaws.com"
                                },
                                "Action": "sts:AssumeRole"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
```

</details>

**Comment by joshlreese** [comment]
# Status Update

## Flatcar Linux

The most closely aligned AMI to Container OS (used in GCP) is [Flatcar Linux](https://www.flatcar.org), which maintains a set of [AMIs for AWS](https://www.flatcar.org/docs/latest/installing/cloud/aws-ec2/).

Flatcar instructs users to define desired configuration via [Butane configurations](https://www.flatcar.org/docs/latest/provisioning/config-transpiler/configuration/), and then transpile them to [Ignition configurations](https://www.flatcar.org/docs/latest/provisioning/ignition/specification/). There is a [cloud-init](https://github.com/flatcar/coreos-cloudinit) module, but after (short) research it does not appear to be bundled in with the OS.

I was able to successfully demonstrate booting Flatcar, disabling undesired services, setting the hostname, and starting kubelet with a static pod manifest via the following Butane config:

<details>
<summary>Butane</summary>

```yaml
---
variant: flatcar
version: 1.0.0
systemd:
  units:
  - name: amazon-ssm-agent.service
    enabled: false
    mask: true
passwd:
  users:
  - name: jreese
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEYFsOfQAvweeGy/Z3q7KdFmnG7lyGsJXikjEeEXuNQp jreese@datum.net
    groups:
    - sudo
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      overwrite: true
      contents:
        inline: jreese-test-instance-us-east-1
    # TODO(jreese) resolv.conf addition for <instance>.<namespace>.<projectName>.cloud.datum-dns.net
    - path: /etc/tmpfiles.d/10-kubelet-prep.conf
      mode: 0644
      contents:
        inline: |
          # Remove kubeadm init concerns
          r /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          r /etc/sysconfig/kubelet
    - path: /etc/systemd/system/kubelet.service.d/10-kubelet-args.conf
      mode: 0644
      contents:
        inline: |
          [Service]
          ExecStart=
          ExecStart=/opt/bin/kubelet --config /var/lib/kubelet/config.yaml --cloud-provider=""
    - path: /var/lib/kubelet/config.yaml
      mode: 0644
      contents:
        inline: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
          authentication:
            webhook:
              enabled: false
          authorization:
            mode: AlwaysAllow
          enableServer: false
          podCIDR: 10.42.0.0/24
          staticPodPath: /etc/kubernetes/manifests
          cgroupDriver: systemd
    - path: /etc/kubernetes/manifests/instance.yaml
      mode: 0644
      contents:
        inline: |
          apiVersion: v1
          kind: Pod
          metadata:
            creationTimestamp: null
            name: instance
            namespace: default
          spec:
            containers:
            - image: mccutchen/go-httpbin
              name: httpbin
              resources: {}
            hostNetwork: true
          status: {}

```

</details>

>[!NOTE]
> We would still like to explore [Talos Linux](https://www.talos.dev/) as an alternative, standard OS.

## VPCs

### Internet Gateways

AWS requires that an [Internet Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html) is associated with a VPC, and that [route tables be updated](https://docs.aws.amazon.com/vpc/latest/userguide/working-with-igw.html#routing-igw) for instances to have external connectivity. Each individual VPC must have its own Internet Gateway configured.

Aside from egress fees, there is no additional cost.

### Network Interfaces

In AWS, Elastic Network Interfaces (ENIs) are first class entities with their own lifecycles. They may be automatically created as a side effect of creating an instance, attached to instances at time of creation, or attached / detached at any time after.

Some network interfaces support exposing multiple _network cards_. When attaching to an instance, a network card index must be specified. We don't currently have a use case for this capability, but it should be noted. Read more at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#network-cards

#### Multi-homed instances

AWS supports attaching more than one network interface to specific instance types. An easy way to determine how many ENIs an instance type supports is by using the aws CLI:

```shell
aws ec2 describe-instance-types \
    --query "InstanceTypes[].{ \
        Type: InstanceType, \
        MaxENI: NetworkInfo.MaximumNetworkInterfaces, \
        IPv4addr: NetworkInfo.Ipv4AddressesPerInterface}" \
    --output table
```

Note - the ENI limit is separate from a _network card_ limit.

#### External IPs

AWS supports management of external IPs via [Elastic IP addresses](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) (EIP). An EIP may be attached or detached from a network interface at any time.

Under certain circumstances, AWS supports automatically associating a public IP address with the primary network interface of an instance. This is influenced by either settings in the instance creation request, or by settings on the subnet an instance is attached to. These IP addresses DO NOT show up as EIPs in the system, and cannot be retained beyond the lifetime of an instance.

When providing more than one network interface, there is no option to automatically associate a public IP at time of instance creation. Instead, an EIP must be created and attached to the desired network interface. This is due to concerns around ambiguous routing when there may be multiple paths to the external network.

> You can't auto-assign a public IP address if you specify more than one network interface. Additionally, you cannot override the subnet setting using the auto-assign public IP feature if you specify an existing network interface for device index 0.

See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/working-with-ip-addresses.html#public-ip-addresses for more details.

### Security Groups

AWS supports very flexible network filtering capabilities via [Security Groups](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html). A security group may have multiple ingress and egress rules that apply restrictions to many protocols.

A security group exists within a VPC, which will require that Datum Network Policies be programmed across all VPCs within the logical Datum Network with resources applicable to each policy.

#### Security Group Usage

An ENI may be associated with zero or more security groups. 

From https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html:

> When you associate multiple security groups with a resource, the rules from each security group are aggregated to form a single set of rules that are used to determine whether to allow access.

During testing, it was identified that a security group must be created to permit egress traffic outside of the VPC network. This is a positive security posture.

## Testing with Crossplane

The manifests below configure the following:

- An Elastic IP to obtain an external IP address, targeting a network interface that will be created.
- A security group with rules that permit access to SSH and port 8080 from the internet, as well as egress access to the internet. These could be in separate security groups, with network interfaces associated with each.
- A network interface to serve as the primary interface for an instance.
- A network interface to serve as a secondary interface for an instance.
- An instance that attaches to the above network interfaces.

<details>
<summary>Crossplane manifests</summary>

```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: jreese-test-eip
spec:
  forProvider:
    domain: vpc
    region: us-east-1
    networkInterfaceRef:
      name: jreese-test-instance-us-east-1-eth0
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
# Security Group
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: jreese-test
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: jreese-test-vpc-us-east-1
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
# Security Group Rule
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: jreese-test-allow-ssh
spec:
  forProvider:
    region: us-east-1
    cidrBlocks:
      - 0.0.0.0/0
    # ipv6CidrBlocks
    protocol: tcp
    fromPort: 22
    toPort: 22
    type: ingress
    securityGroupIdRef:
      name: jreese-test
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: jreese-test-allow-container-port
spec:
  forProvider:
    region: us-east-1
    cidrBlocks:
      - 0.0.0.0/0
    # ipv6CidrBlocks
    protocol: tcp
    fromPort: 8080
    toPort: 8080
    type: ingress
    securityGroupIdRef:
      name: jreese-test
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: jreese-test-allow-egress
spec:
  forProvider:
    region: us-east-1
    cidrBlocks:
      - 0.0.0.0/0
    # ipv6CidrBlocks
    fromPort: 0
    toPort: 65535
    protocol: all
    type: egress
    securityGroupIdRef:
      name: jreese-test
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  name: jreese-test-instance-us-east-1-eth0
spec:
  forProvider:
    region: us-east-1
    subnetIdRef:
      name: jreese-test-vpc-us-east-1-subnet-0
    securityGroupRefs:
      - name: jreese-test
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  name: jreese-test-instance-us-east-1-eth1
spec:
  forProvider:
    region: us-east-1
    subnetIdRef:
      name: jreese-test-vpc-us-east-1-subnet-0
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project
---
apiVersion: ec2.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: jreese-test-instance-us-east-1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    ami: ami-003496bc8140c472c
    # instanceType: t2.micro
    instanceType: t3a.micro
    # Note - changes to this will recreate the instance, use NetworkInterfaceAttachment to adjust
    networkInterface:
      - networkCardIndex: 0
        deviceIndex: 0
        networkInterfaceIdRef:
          name: jreese-test-instance-us-east-1-eth0
      - networkCardIndex: 0
        deviceIndex: 1
        networkInterfaceIdRef:
          name: jreese-test-instance-us-east-1-eth1
    userData: |-
      {
        "ignition": {
          "version": "3.3.0"
        },
        "passwd": {
          "users": [
            {
              "groups": [
                "sudo"
              ],
              "name": "jreese",
              "sshAuthorizedKeys": [
                "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEYFsOfQAvweeGy/Z3q7KdFmnG7lyGsJXikjEeEXuNQp jreese@datum.net"
              ]
            }
          ]
        },
        "storage": {
          "files": [
            {
              "overwrite": true,
              "path": "/etc/hostname",
              "contents": {
                "compression": "",
                "source": "data:,jreese-test-instance-us-east-1"
              },
              "mode": 420
            },
            {
              "path": "/etc/tmpfiles.d/10-kubelet-prep.conf",
              "contents": {
                "compression": "",
                "source": "data:,%23%20Remove%20kubeadm%20init%20concerns%0Ar%20%2Fetc%2Fsystemd%2Fsystem%2Fkubelet.service.d%2F10-kubeadm.conf%0Ar%20%2Fetc%2Fsysconfig%2Fkubelet%0A"
              },
              "mode": 420
            },
            {
              "path": "/etc/systemd/system/kubelet.service.d/10-kubelet-args.conf",
              "contents": {
                "compression": "",
                "source": "data:,%5BService%5D%0AExecStart%3D%0AExecStart%3D%2Fopt%2Fbin%2Fkubelet%20--config%20%2Fvar%2Flib%2Fkubelet%2Fconfig.yaml%20--cloud-provider%3D%22%22%0A"
              },
              "mode": 420
            },
            {
              "path": "/var/lib/kubelet/config.yaml",
              "contents": {
                "compression": "gzip",
                "source": "data:;base64,H4sIAAAAAAAC/0zQsW4yMRAE4N5P4SewAVH8cofgL6I0iEjpffYetzrf7sm75kKePuJQULopvpli4oyfUAWZgh1bBwXUJaYer278Jw7Z37YdaNyaESkH+/40x5W0GhWZTGLSiAT10khxgv+UZ0bSYBvhV/De10b+pfKf6ITTaGLTAUgxrXvBWLtANzCPj2gtUOwK5GD7WARWzRW/X3jiDMEeyhLvciiFF/NsfEC9Qf2tzZyPb6dLsNuN2+/cxm38bm9Eo2I6cz5HHYL1oMk/jqgECuKnSNiDqJh0rdzmU8V1Uu6iMGXzEwAA//9KCXWZQAEAAA=="
              },
              "mode": 420
            },
            {
              "path": "/etc/kubernetes/manifests/instance.yaml",
              "contents": {
                "compression": "gzip",
                "source": "data:;base64,H4sIAAAAAAAC/0zMTUoFMRDE8X1OURd4iNs+hLgQ922mfNPMpBPSHV2Idxe/4C3rX/DTYc+cYd0Fb/flMN8Ej30rjambpkoB6qSmdX+yxkhtQ+DrPAvg2igwj1Sv/AsxtFKw8VXXmSUG64/SPdWcM77XBdb0SkGrdWXd6XfXftkzx4t5Af7t2zIZfc3KEHx8FmDvkQ/M9z4PQc7FEqm5fu+vAAAA///+v1Zc2gAAAA=="
              },
              "mode": 420
            }
          ]
        },
        "systemd": {
          "units": [
            {
              "enabled": false,
              "mask": true,
              "name": "amazon-ssm-agent.service"
            }
          ]
        }
      }
  providerConfigRef:
    name: project-test-fz3pr6-demo-aws-project

```

</details
