### ISSUE TITLE
Anycast'd DNS service

### ISSUE THREAD

**Issue by scotwells** [datum-cloud/enhancements#15]

**Comment by joshlreese** [comment]
The [external-dns](https://kubernetes-sigs.github.io/external-dns/latest/) project has support for configuring DNS servers via [RFC 2136 Dynamic Updates](https://tools.ietf.org/html/rfc2136), which both Hickory DNS and KnotDNS support (among many other servers). 

The [external-dns.alpha.kubernetes.io/hostname](https://kubernetes-sigs.github.io/external-dns/latest/docs/annotations/annotations/#external-dnsalphakubernetesiohostname) annotation can be used to directly influence DNS records created for resources such as a `Gateway`. There is also a [DNSEndpoint](https://kubernetes-sigs.github.io/external-dns/latest/docs/contributing/crd-source/) custom resource type that can be used for defining arbitrary record information.

I plan to perform a POC showing an `external-dns` managed deployment of Hickory DNS (or alternatively KnotDNS if challenges are encountered), creating DNS records as a result of a `Gateway` resource being created. I expect to deploy this as a DaemonSet, where `external-dns` is colocated with the DNS server.

**Comment by joshlreese** [comment]
I've gotten to the point that I can have external-dns connect to Hickory DNS and load zone information via AXFR. Unfortunately, Dynamic DNS updates are not working as Hickory only supports [SIG(0)](https://datatracker.ietf.org/doc/html/rfc2931), and external-dns only supports [TSIG](https://datatracker.ietf.org/doc/html/rfc2845) and [GSS-TSIG](https://en.wikipedia.org/wiki/Generic_Security_Service_Algorithm_for_Secret_Key_Transaction).

It appears that SIG(0) auth is public key based, whereas TSIG is a shared secret with an hmac. The code in external-dns for RFC 2136 compliant servers is located [here](https://github.com/kubernetes-sigs/external-dns/blob/master/provider/rfc2136/rfc2136.go), and I don't expect it would be a huge effort to add SIG(0) support.

I'll be shifting to evaluate configuring KnotDNS via RFC 2136 next.

The k8s manifests I used to test this are below:

<details>
<summary>Manifests</summary>

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-dns
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hickory-dns
data:
  config.toml: |
    log_level = "trace"

    [[zones]]
    zone = "example.com"

    zone_type = "Primary"

    file = "example.com.zone"

    allow_axfr = true

    [zones.stores]
    type = "sqlite"
    zone_file_path = "example.com.zone"
    journal_file_path = "/journals/example.com_dnssec_update.jrnl"
    allow_update = true

    #[[zones.keys]]
    #key_path = "/tmp/rsa_2048.pk8"
    #algorithm = "RSASHA256"
    #signer_name = "externaldns"
    #purpose = "ZoneUpdateAuth"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hickory-dns-zone
  labels:
    hickory-dns: ""
data:
  example.com.zone: |
    ; replace the hickory-dns.org with your own name
    @   IN          SOA     hickory-dns.org. root.hickory-dns.org. (
                                    199609203 ; Serial
                                    8h        ; Refresh
                                    120m      ; Retry
                                    7d        ; Expire
                                    24h)      ; Minimum TTL

                    NS      bbb

                    MX      1 alias

                    ANAME   www

    www             A       127.0.0.1
                    AAAA    ::1

    bbb             A       127.0.0.2
    this.has.dots   A       127.0.0.4

    alias           CNAME   www
    alias-chain     CNAME   alias

    aname-chain     ANAME   alias

    ; _Service._Proto.Name TTL Class SRV Priority Weight Port Target
    server          SRV     1 1 443 alias

    *.wildcard      CNAME   www

    no-service 86400 IN MX 0 .
---
apiVersion: v1
kind: Pod
metadata:
  name: hickory-dns
spec:
  serviceAccountName: external-dns
  containers:
  - name: hickory-dns
    image: docker.io/library/hickory-dns:v0.0.1-3
    args:
      - -c
      - /config/config.toml
      - -z
      - /zones
      # - -d
    ports:
    - containerPort: 53
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: config
        mountPath: /config
      - name: zones
        mountPath: /zones
      - name: journals
        mountPath: /journals
  - name: external-dns
    image: registry.k8s.io/external-dns/external-dns:v0.15.1
    args:
      - --log-level=debug
      - --log-format=text
      - --interval=1m
      - --policy=sync
      - --provider=rfc2136
      - --source=gateway-httproute
      - --rfc2136-host=127.0.0.1
      - --rfc2136-port=53
      - --rfc2136-zone=example.com
      - --rfc2136-insecure
      # - --rfc2136-tsig-secret=96Ah/a2g0/nLeFGK+d/0tzQcccf9hCEIy34PoXX2Qg8=
      # - --rfc2136-tsig-secret-alg=hmac-sha256
      # - --rfc2136-tsig-keyname=externaldns
      - --rfc2136-tsig-axfr
    # env:
    #   - name: GODEBUG
    #     value: http2debug=2
  volumes:
    - name: config
      configMap:
        name: hickory-dns
    - name: zones
      configMap:
        name: hickory-dns-zone
    - name: journals
      emptyDir: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-web
spec:
  gatewayClassName: eg
  listeners:
  - protocol: HTTP
    port: 80
    name: prod-web-gw
    allowedRoutes:
      namespaces:
        from: Same
  addresses:
    - type: IPAddress
      value: 1.2.3.4
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo
  annotations:
    external-dns.alpha.kubernetes.io/target: 1.1.1.1
spec:
  parentRefs:
  - name: prod-web
  hostnames:
  - test.example.com
  rules:
  - backendRefs:
    - name: backend
      port: 3000

```

</details>

The Dockerfile I used for building Hickory DNS is below:

```dockerfile
FROM rust:1.85 AS builder

WORKDIR /app

COPY ./bin /app/bin
COPY ./conformance /app/conformance
COPY ./crates /app/crates
COPY ./fuzz /app/fuzz
COPY ./scripts /app/scripts
COPY ./tests /app/tests
COPY ./util /app/util
COPY ./Cargo.lock /app/Cargo.lock
COPY ./Cargo.toml /app/Cargo.toml

RUN cargo build --release -p hickory-dns --all-features

FROM ubuntu:24.04

RUN groupadd nobody
RUN apt-get update && apt-get install -y dnsutils

COPY --from=builder /app/target/release/hickory-dns /hickory-dns

ENTRYPOINT [ "/hickory-dns" ]
```

**Comment by joshlreese** [comment]
I've got the very beginnings of a POC with external-dns colocated with KnotDNS, and reconciling records into a zone.

<details>
<summary>Manifests</summary>

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-dns
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knotdns
data:
  knot.conf: |
    server:
        listen: 0.0.0.0@53
        listen: ::@53

    # TODO(jreese) These keys can probably be loaded into a file via secrets, and
    # included from here.
    key:
      - id: externaldns
        algorithm: hmac-sha256
        secret: 96Ah/a2g0/nLeFGK+d/0tzQcccf9hCEIy34PoXX2Qg8=

    acl:
      - id: update_acl
        address: 127.0.0.1/32
        key: externaldns
        action: [transfer, update]

    zone:
      - domain: example.com
        storage: /zones
        acl: update_acl

    log:
      - target: stdout
        any: debug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knotdns-zones
data:
  example.com.zone: |
    @   IN          SOA     knotdns.org. root.knotdns.org. (
                                    199609203 ; Serial
                                    8h        ; Refresh
                                    120m      ; Retry
                                    7d        ; Expire
                                    24h)      ; Minimum TTL

                    NS      bbb
---
apiVersion: v1
kind: Pod
metadata:
  name: knotdns
spec:
  serviceAccountName: external-dns
  containers:
  - name: knotdns
    image: cznic/knot:3.4
    command:
      - /usr/sbin/knotd
    args:
      - -c
      - /config/knot.conf
    ports:
    - containerPort: 53
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: config
        mountPath: /config
      - name: zones
        mountPath: /zones
  - name: external-dns
    image: registry.k8s.io/external-dns/external-dns:v0.15.1
    args:
      - --log-level=debug
      - --log-format=text
      - --interval=1m
      - --policy=sync
      - --provider=rfc2136
      - --source=gateway-httproute
      - --rfc2136-host=127.0.0.1
      - --rfc2136-port=53
      - --rfc2136-zone=example.com
      - --rfc2136-tsig-secret=96Ah/a2g0/nLeFGK+d/0tzQcccf9hCEIy34PoXX2Qg8=
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=externaldns
      - --rfc2136-tsig-axfr
    # env:
    #   - name: GODEBUG
    #     value: http2debug=2
  volumes:
    - name: config
      configMap:
        name: knotdns
    - name: zones
      configMap:
        name: knotdns-zones
    - name: journals
      emptyDir: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-web
spec:
  gatewayClassName: eg
  listeners:
  - protocol: HTTP
    port: 80
    name: prod-web-gw
    allowedRoutes:
      namespaces:
        from: Same
  addresses:
    - type: IPAddress
      value: 1.2.3.4
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo
  annotations:
    external-dns.alpha.kubernetes.io/target: 1.1.1.1
spec:
  parentRefs:
  - name: prod-web
  hostnames:
  - test.example.com
  rules:
  - backendRefs:
    - name: backend
      port: 3000

```

</details>

```shell
% kubectl exec knotdns -c knotdns -it -- dig @127.0.0.1 test.example.com +short
1.2.3.4
```

One item to point out is that the `external-dns.alpha.kubernetes.io/target` annotation is not being obeyed. I suspect there's a config setting I need to adjust in external-dns.
